
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you'd want to handle this more gracefully.
  // For this context, we assume the API key is provided.
  throw new Error("API_KEY is not set in environment variables.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const helpText = `
Kali Linux Command Simulator - Help

This simulator provides a safe environment to learn basic Linux commands.
The output for commands not listed here is generated by an AI.

File System Commands:

  ls [-a]           - Lists files and directories in the current location.
                      -a: shows all files, including hidden ones.

  cd <dir>          - Changes the current directory. Supports '..', '~', and absolute/relative paths.

  cat <file>        - Displays the contents of a file.

  pwd               - Prints the full path of the current working directory.

  mkdir <dir>       - Creates a new directory.

Other Commands:

  whoami            - Displays the username of the current user.

  neofetch          - Shows a summary of system information in a visually appealing way.

  apt update        - Refreshes the list of available software packages from repositories.

  apt install <pkg> - Simulates the installation of a software package (e.g., 'apt install htop').

  ping <host>       - Checks network connectivity to a specified host (e.g., 'ping google.com').

  help              - Shows this help message with all available commands.

  clear             - Clears the terminal screen, removing all previous output.

Git Commands:

  git status        - Shows the status of changes as untracked, modified, or staged.

  git diff          - Shows changes between commits, commit and working tree, etc.
  
  git commit -m "<msg>"- Records changes to the repository with a message.

  git log           - Displays a log of the commit history.

  git branch        - Lists all local branches and highlights the current one.

  git clone <repo>  - Clones a repository into a new directory with simulated progress.

  git push          - Simulates pushing commits to a remote repository.

  git pull          - Simulates fetching and merging changes from a remote repository.
  
  git fetch         - Downloads commits and objects from a remote repository.

Termux Commands:

  termux-fix-shebang <file> - Rewrites the shebang of a script for Termux.
`;


export async function simulateCommandOutput(command: string): Promise<string> {
  const model = 'gemini-3-flash-preview';

  if (command.trim().toLowerCase() === 'help') {
    return Promise.resolve(helpText);
  }

  const prompt = `
You are an AI assistant role-playing as a Kali Linux terminal simulator for a web application.
Your purpose is to generate safe, fictional, and illustrative terminal output for common Linux commands.
The output should look realistic but must be completely simulated.

IMPORTANT SAFETY RULES:
- Do NOT generate any real passwords, private keys, or sensitive credentials.
- Do NOT generate any output that could be misconstrued as malicious code or hacking activity.
- All output must be clearly identifiable as a fictional simulation.
- Stick to the requested command and do not execute or simulate unrelated or harmful commands.

Generate the simulated output for the following command. Provide only the raw, formatted text output as if it were printed directly to a terminal. Do not include any explanations, introductory text, or markdown formatting.

Command: \`${command}\`
`;
  
  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });
    
    if (response && response.text) {
      return response.text;
    }
    return "No output received from the model.";

  } catch (error) {
    console.error("Gemini API call failed:", error);
    return `Error: Could not simulate command. Please check your API key and network connection. Details: ${error instanceof Error ? error.message : String(error)}`;
  }
}
